import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Roboto } from "next/font/google";
import Footer from "./components/Footer";
import ToastContainerWrapper from "./components/ToastContainerWrapper";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} h-[100dvh]`}>
        <Navbar />
        <main>{children}</main>
        <Footer />
        <ToastContainerWrapper />
      </body>
    </html>
  );
}
